name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Matches the stable version in RHEL 9.x

      - name: Download dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v ./...

      - name: Run Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  build:
    name: Build Binary
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Download dependencies
        run: go mod download

      - name: Build Binary
        run: go build -o server ./cmd/api
        # This will now succeed because we have a valid main.go
